### ISSUE TITLE
Missing shebang line in bin/run

### ISSUE THREAD

**Issue by rjcolmed** [learn-co-students/dynamic-orms-readme-v-000#584]
The shebang line (#!/usr/bin/env ruby) seems to be missing from this lab's bin file. I was not able to run the file until I added it. Not sure if this is by design (to get us to think more critically to solve issues) or an oversight. Not a huge deal, but just FYI!

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
