### ISSUE TITLE
Active_support dependency missing from Gemfile

### ISSUE THREAD

**Issue by thegands** [learn-co-students/dynamic-orms-readme-v-000#82]
Running `ruby bin/run` fails to execute even after running `bundle install` because activesupport is not included in the gemfile. It should be declared as a dependency so executing the run file will work after using `bundle install`.

**Comment by lisaychuang** [comment]
I've also noted in ```bin/run```, the require_relative paths should be updated to:

require_relative "./lib/song.rb"
require_relative "./config/environment.rb"

**Comment by cassaram09** [comment]
Has this been resolved yet? Another student pointed out the dependency error.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
